//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Introduzione {
	
	
	public partial class Import {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label LBLLoggedName;
		
		protected System.Web.UI.WebControls.TextBox TXTUsername;
		
		protected System.Web.UI.WebControls.TextBox TXTPsw;
		
		protected System.Web.UI.WebControls.TextBox TXTNome;
		
		protected System.Web.UI.WebControls.TextBox TXTCognome;
		
		protected System.Web.UI.WebControls.TextBox TXTEta;
		
		protected System.Web.UI.WebControls.Button BTNSubmit;
		
		protected System.Web.UI.WebControls.Label LBLOutput;
		
		protected System.Web.UI.WebControls.Button BTNSubmitTab;
		
		protected System.Web.UI.WebControls.GridView GRDPerson;
	}
}
